#!/bin/bash

# Script para configurar webhook en ThingSpeak
# Esto requiere configuración manual en ThingSpeak

echo "🔧 Configuración de Webhook ThingSpeak → Supabase"
echo "=================================================="
echo ""
echo "Para configurar la sincronización automática en tiempo real:"
echo ""
echo "1. Ir a https://thingspeak.com/channels/2988488"
echo "2. Ir a Apps > ThingHTTP"
echo "3. Crear nueva ThingHTTP con estos datos:"
echo ""
echo "   Name: Sync to Supabase"
echo "   URL: https://phmetro.vercel.app/api/thingspeak-webhook"
echo "   HTTP Auth Username: (dejar vacío)"
echo "   HTTP Auth Password: (dejar vacío)"
echo "   Method: POST"
echo "   Content Type: application/json"
echo "   Headers: (dejar vacío)"
echo "   Body: %%channel_%%"
echo ""
echo "4. Ir a Apps > React"
echo "5. Crear nueva React con estos datos:"
echo ""
echo "   React Name: Auto Sync Supabase"
echo "   Condition Type: On Data Insertion"
echo "   Test Frequency: On Data Insertion"
echo "   Condition: always"
echo "   Action: ThingHTTP"
echo "   ThingHTTP: Sync to Supabase"
echo "   Options: Run action each time condition is met"
echo ""
echo "✅ Una vez configurado, los datos se sincronizarán automáticamente"
echo "   cada vez que Arduino envíe datos a ThingSpeak"
echo ""
echo "📊 URLs importantes:"
echo "   - Dashboard: https://phmetro.vercel.app/"
echo "   - Sync Manual: https://phmetro.vercel.app/api/sync-thingspeak"
echo "   - Webhook: https://phmetro.vercel.app/api/thingspeak-webhook"
echo ""
echo "🔄 Mientras tanto, la sincronización local sigue funcionando cada 30s"
